### ISSUE TITLE
 ls ;            ;       ls

### ISSUE THREAD

**Issue by Gwojda** [jzck/42sh#102]
➜  42sh git:(master) ✗ ls ;            ;       ls
syntax error near unexpected token `;'

->doit afficher 2 ls

**Comment by Gwojda** [comment]
dans le meme genre : 
➜  42sh git:(master) ✗ ls ;; ls
ls: ls: No such file or directory

**Comment by ariard** [comment]
la premiere est bon, la deuxieme je corrige

**Comment by wescande** [comment]
pour la deuxieme, maintenant il n'y a pas d'affichage de message d'erreur, ni d'affichage du ls.

**Comment by jzck** [comment]
je le met dans #53
