### ISSUE TITLE
reset ast

### ISSUE THREAD

**Issue by wescande** [jzck/42sh#111]
```
➜  42sh git:(master [ahead 1]) ✗ while [ 1 ]
>
➜  42sh git:(master [ahead 1]) ✗ ls
>
```

apres avoir tapé while, j'ai validé, puis j'ai fait ctrl-C et la commande suivante considere qu'on est encore dnas le while :/

**Comment by jzck** [comment]
bonus: il faut aussi reset les structures `lexer`, `parser` et la liste des tokens

**Comment by jzck** [comment]
ne vaudrait-il pas mieux sortir completement de la fonction `handle_instruction` dans le cas où on appuie sur ctrl-c ?
