### ISSUE TITLE
Launching 42sh under Sierra lead to an abort

### ISSUE THREAD

**Issue by m600x** [jzck/42sh#113]
pointer being freed was not allocated

![alt text](http://reho.st/self/9e9f39110e0c3c453e31ab316af7bfa85b6f1797.png "make")
![alt text2](http://reho.st/self/e0e90842469637478340cbb00f95afc12c45524d.png "lldb")

Macbook Pro 15 Retina
Lasted OSX Sierra 10.11.

Je précise que les précédentes versions fonctionnaient sur le meme mac hein :v

**Comment by wescande** [comment]
Que dit valgrind ? qu'est-ce qui a été free ?

**Comment by m600x** [comment]
Quand j'ai testé valgrind ne se lancait pas (mmap_fixed je sais pas quoi). Mais possible que la version installé est outdated. Je pourrais revoir ça ce soir.

**Comment by wescande** [comment]
Ou alors mets des debug toutes les lignes de chaque fonction pour voir sur quoi ca segv...
avec ta capture on sait juste que ta copine/maman/fille (l'un n'empêche pas forcement l'autre) s'appelle Emeline :D

**Comment by Gwojda** [comment]
Normalement c'est résolu, je te laisse me confirmer quand tu pourras @m600x 
J'suis désolé, j'avais retiré la protection sur le retour d'open pendant la mise a la norme, et j'ai oublié de la remettre.. x(

**Comment by m600x** [comment]
Bno, au moins nous savons que wescande a pas trop de probleme avec l'insceste :rofl: 

Mais j'ai pu vérifier rapidement ce matin sans pour autant avoir le temps de dire ce qui merde. Donc je dump ce que j'ai eu le temps de voir.

@Gwojda Je retesterais ce soir!

**Comment by jzck** [comment]
pour info: valgrind ne fonctionne pas normalement sous Sierra... ou alors il faut faire des reglages speciaux mai j'ai jamais essayé

**Comment by Gwojda** [comment]
C'est resolu @m600x ?

**Comment by m600x** [comment]
Fixed.
