### ISSUE TITLE
catch abort / segv ?

### ISSUE THREAD

**Issue by wescande** [jzck/42sh#115]
lorsque un programme a l'interieur du shell segv ou abort , on n'affiche pas le petit messaginous

**Comment by jzck** [comment]
ah ouais j'ai mis le message de "pid terminated with signal X" seulement en mode debug, faudrait que je l'active en cas de segv/abort, je vais voir si yen a d'autres a afficher

**Comment by Gwojda** [comment]
On peut close ? Les segv, broken pipe, etc ont leurs ptits messages maintenant
