### ISSUE TITLE
historique des case

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#117]
quand je passe : case tutu in \n
( tutu ) ls ;; \n 
esac

et qu ensuite j utilise l historique cela me sors un

**Comment by wescande** [comment]
idem pour les while
```
while [ 1  ]
do
ls
done
```
Puis en revenant dessus, si le curseur est sur la premiere ligne, il considere que la commande n4est pas complete

**Comment by Gwojda** [comment]
J'envois 
`while [ 1  ]\n
do\n
ls\n
done\n`
Pour l'exemple de wescande, je ne pense pas que le probleme vienne de l'historique

exemple : si je rajoute un ; a la fin du ls dans la chaine que recup de l'histo, et que je retire les `\n`, cela fonctionne
