### ISSUE TITLE
erreur exit status

### ISSUE THREAD

**Issue by Gwojda** [jzck/42sh#120]
`|| ls` -> exit status = 0
`ls &&& ls` ->exit status = 0

**Comment by wescande** [comment]
en fait c'est sur toutes les erreurs de syntaxe.
donc @ariard  :)

**Comment by jzck** [comment]
putain on avait pas capté ces erreurs là...

gwojda: l'execution recoit n'importe quoi donc c'est normal que l'exitstatus soit n'importe quoi (le parser devrait gueuler avec ca)
