### ISSUE TITLE
env ./42sh

### ISSUE THREAD

**Issue by Gwojda** [jzck/42sh#122]
-> affiche le resultat a la fin du ./42sh

**Comment by wescande** [comment]
impossible a reproduire sur linux. je verrais demain a 42

**Comment by wescande** [comment]
@Gwojda 
J'ai fix pas mal de choses qui se cachaient sous ce petit probleme, mais j'ai un soucis et je pense que tu peux m'aider.
Quand je fais `env ./42sh`, tout se passe bien, mais au moment ou je le quitte (exit ou ctrl-d) il me ferme aussi le pere...
Tu as une idée?

**Comment by wescande** [comment]
@jzck apparemment on sort sur le read qui renvoi -1.
Je ne comprend pas pourquoi. 
Je tourne en rond dessus 💀
