### ISSUE TITLE
Launching with /dev/urandom is not protected

### ISSUE THREAD

**Issue by m600x** [jzck/42sh#125]
`./42sh < /dev/urandom`

The Shell doesn't exit if foreign or weird things is thrown at it. It will keep trying to execute all the command and finally will infinite loop somewhere.

zsh and bash automatically quit if such input is detected.

**Comment by Gwojda** [comment]
avec fsanitize=address ->segv
sans, deux cas : 
-> On boucle inf arrivé a un moment
-> On quitte a un moment donné (et echo $? renvoit 1)
