### ISSUE TITLE
cat + ctrl c ne tue pas le process SI

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#128]

**Comment by ariard** [comment]
rm nosuchfile 2>&1 | cat -e
cat -e << EOF
base64 /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e 's/1/Yes/g' -e 's/0/No/g'

**Comment by Gwojda** [comment]
Le premier marche aussi pr moi
Le 2nd, ne vaudrait-il pas juste retirer le msg d'erreur en cas de broken pipe ?

**Comment by jzck** [comment]
j'ai enlevé le message pour les brokenpipe (SIGPIPE = signal no. 13)
