### ISSUE TITLE
apparation random de valeurs dans l edition de ligne quand deplacement rapide 

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#134]
genre aaaaaaaa[D[D[D ou bbbbbb[C[C[C 
teste sur El Capitan Mac Book Air, 
![capture d ecran 2017-03-21 a 23 45 52](https://cloud.githubusercontent.com/assets/23310655/24177142/b2d80104-0ea0-11e7-96bc-953c6330f111.png)
sur Iterm en azerty

**Comment by Gwojda** [comment]
Les valeurs des touches se mettent en file d'attente quand on écrit tres vite le temps qu'on traite les infos une par une, du coup si jamais tu fais des fleches et des écritures en boucles, je vais lire un int plus important, et je vais rentrer en mode "lecteur de C/C externe", et donc decomposer en char et les ajouter
Se sont les valeurs des touches des fleches gauches droites ici, donc
J'avais réussi a le faire plusieurs fois sur zsh aussi, et plus la ligne est longue, plus on est long a la traiter.. Donc je sais pas trop ce que je peux y faire

**Comment by jzck** [comment]
tu peux essayer de faire varier `term.c_cc[VTIME]` pour changer le temps de declenchement de read mais je doute que tu puisse faire grand chose

**Comment by ariard** [comment]
ok j ai pas le probleme a l ecole donc je close aussi
