### ISSUE TITLE
copier/coller/cut selection ?

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#137]
comment faire ? j arrive pas a m en servir

**Comment by Gwojda** [comment]
le copier coller externe, cad `command + c` ou `command + v` fonctionne normalement comme pr les autres apps
le copier couper coller interne au shell, je prends toutes les elements qui suivent le curseur et je les garde en memoire

Exemple 
`aaaaa[curseur]bbbbb`
Si j'appuie sur `option + x` je vais voir la chaine suivante
`aaaaa[curseur]` et j'aurai en tampon `bbbbb`
Et si j'appuies sur `option + v` j'aurai alors `bbbbb` qui s'ajoutera a la chaine

**Comment by Gwojda** [comment]
Normalement il n'y a plus de décalage
Je vais ajouter les fleches haut et bas dans la journée

-> les controls sont les suivants
Option + c debut du mode inverse (option + x aussi, mais les caracteres surlignés seront supprimés de la chaine apres)
Mouvement avec les fleches + home et end 
En cas d'appuies d'une touche différente, sortie du mode et enregistrement des chars surlignés (et suppression dans la chaine si option + x)

Option + v n'a pas changé, il colle juste la chaine tampon dans la chaine d'entrée
