### ISSUE TITLE
quote et inihibteur, sortie differentes de zsh

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#140]
![capture d ecran 2017-03-22 a 00 25 56](https://cloud.githubusercontent.com/assets/23310655/24177263/9780a964-0ea1-11e7-96c8-2a54fadaf4f4.png)

**Comment by ariard** [comment]
![capture d ecran 2017-03-22 a 00 26 01](https://cloud.githubusercontent.com/assets/23310655/24177272/a0cc6292-0ea1-11e7-86ae-90c259c597d5.png)

**Comment by jzck** [comment]
perso j'arrive pas a reproduire j'ai la meme sortie que bash/zsh

**Comment by Gwojda** [comment]
pareil

**Comment by ariard** [comment]
ok pareil aussi a l ecole en test sur bash, je ferme
