### ISSUE TITLE
expansion violente : */*/*/*/*

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#142]
*/*/*/*/*/* + tab

ou bien
 ls /*/*/*

= crash

**Comment by m600x** [comment]
Si je fais `ls /Applications/*[tab]` la completion est bloqué parce que la ligne de commande résultante est supérieur à 512 caractères chez moi.

**Comment by Gwojda** [comment]
@wescande 
J'ai l'impression que c'est `opendir` qui renvoit une erreur et comme tu l'as pas protégé jme demande si c'est pas ca
(en tout cas on crash plus quand je rajoute une protection, si ca peut t'aiguiller)

**Comment by wescande** [comment]
Merci, c'est exactement ca.
