### ISSUE TITLE
big subshell ( ( ( ( ( ( ( ls ) ) ) ) ) ) ) ) ) : leaks + bad math brackets

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#144]

**Comment by jzck** [comment]
on a dit qu'on faisait pas les maths comme ca donc...

**Comment by ariard** [comment]
je voulais dire bad brackets

**Comment by ariard** [comment]
probleme de lexing ( ( ls ) ) ) 
token_print 
paren_open
paren_open
word
paren_close
paren_close

@jzck
