### ISSUE TITLE
leaks : for, math, func

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#149]

**Comment by ariard** [comment]
~~subshell~~
~~brace_clause~~

**Comment by ariard** [comment]
~~var~~

**Comment by ariard** [comment]
~~case~~

**Comment by ariard** [comment]
math VAR + 10
leaks

**Comment by wescande** [comment]
apres le passage de jack, il semble que math ne leaks plus. le seul leaks qu'il y a c'est un ft_itoa direct dans un DG()

**Comment by wescande** [comment]
plus de leaks pour for

**Comment by wescande** [comment]
plus de leaks dans les func
