### ISSUE TITLE
Cannot quit the shell with (1)

### ISSUE THREAD

**Issue by m600x** [jzck/42sh#154]
Launch the shell: `./42sh`
Type the command: `./42sh (1)`
Then: `exit`.
Then retype: `exit`.
Once again, type: `exit`.
Then move the mouse to the upper right corner.
Then type: `exit`.
The resize the terminal to a bigger size.
Then retype: `exit`.
Then give up.

Only Ctrl + D can exit both shell.

**Comment by Gwojda** [comment]
```

➜  42sh git:(master) ✗ ./42sh (1)
syntax error near unexpected token '1'
```

**Comment by Gwojda** [comment]
Alors perso, je lance `./42sh` et ensuite `./42sh (1)` et ca `exit(1)` (meme le premier 42sh)

**Comment by Gwojda** [comment]
```
➜  42sh git:(master) ✗ ./42sh (1)
syntax error near unexpected token `1'
➜  42sh git:(master) ✗ ls
syntax error near unexpected token `1'
➜  42sh git:(master) ✗ ls
syntax error near unexpected token `1'
```

**Comment by jzck** [comment]
perso j'ai besoin d'exit que 2 fois j'arrive pas a reproduire

**Comment by m600x** [comment]
Fix!
