### ISSUE TITLE
leaks bizarre

### ISSUE THREAD

**Issue by wescande** [jzck/42sh#167]
@gwojda 
ça fait plusieurs fois que ca m'arrive, mais de temps en temps j'ai le leaks suivant au demarrage:
le pb c'est que des que j'appuie sur entrée je l'ai de nouveau.
```
leaks Report Version:  2.0
Process 19544: 447 nodes malloced for 124 KB
Process 19544: 1 leak for 16 total leaked bytes.
Leak: 0x7fc4e2500070  size=16  zone: DefaultMallocZone_0x100a5c000
	0x74736100 0x00007265 0x00000000 0x00000000 	.aster..........
```
Je pensais que c'est git car on voit le `aster`.
Et le leaks n'arrive que quand je suis parfaitement a jour de master (un git pull frais sans rien dans le git diff)

**Comment by Gwojda** [comment]
C'etait bien ca, merci @wescande !
