### ISSUE TITLE
ls | wc -l | ls &

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#180]
pas le meme comportement que bash

**Comment by Gwojda** [comment]
Sisi c'est bon
t'exec la commande en arriere plan, et le temps que traite le prompt, la commande se retrouve dedans

Bash -> Il affiche bash, pour le ret de la commande et l'ecriture se fait apres le ret de la commande
-> c'est bon du coup
(je laisse @jzck valider)

**Comment by wescande** [comment]
pour moi c'est bon aussi.
C'est juste qu'on a pas le temps de réafficher tout le prompt.
