### ISSUE TITLE
Job Control: Leaks 1 blocks if job has been terminated elsewhere

### ISSUE THREAD

**Issue by m600x** [jzck/42sh#182]
![screen shot 2017-03-24 at 09 43 52](https://cloud.githubusercontent.com/assets/10199481/24286783/fd2b388e-1076-11e7-9727-0f76ce71b347.png)

**Comment by wescande** [comment]
Valgrind sort des erreurs en quittant, mais je ne vois pas de leaks...
je n'arrive pas a reproduire...

**Comment by wescande** [comment]
j'ai compris ton truc et j'ai corrigé.
@jhalford : j'ai ajouté une ligne a data_exit.
check si j'ai raison d'effacer la liste chaine comme ca.
et si c'est good pour toi alors on close

**Comment by m600x** [comment]
Effectivement, j'ai oublié de mettre la procedure:

`vi`
`Ctrl+Z`
Dans un autre terminal `killall vi`
`fg`
`exit`
