### ISSUE TITLE
urandom deregle les termcaps

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#193]
![screen shot 2017-03-25 at 12 09 26 am](https://cloud.githubusercontent.com/assets/23310655/24316586/685c39e6-10ef-11e7-8a8b-49bc4147e216.png)

**Comment by Gwojda** [comment]
Tu as oublié le / dans sed avec 's/1/Yes/g' ^^
Et sur linux j'ai pas de soucis perso, les autres ont ce problèmes aussi ?
