### ISSUE TITLE
ctrl + D + heredoc

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#194]
Lancez la commande "$> cat -e << EOF", puis entrez le texte 
suivant sans les triples guillemets mais en respectant les 
sauts de lignes : 
""" 
Roses are red 
Violets are blue 
All my base are belong to you 
And so are you 

=> on le passe pas

**Comment by jzck** [comment]
@Gwojda je résume ce qu'il faut: si CTRL D en début de ligne avec un mini-prompt il faut faire comme un ctrl C 

référence bash avec l'exemple ci dessus (heredoc avec ctrl D en debut de ligne)

**Comment by Gwojda** [comment]
Tu es sur ? J'ai l'impression que zsh ne fait rien en cas de control D lorsqu'on est EB attente
