### ISSUE TITLE
Redirection: conditional jump depends on uninitialised value.

### ISSUE THREAD

**Issue by m600x** [jzck/42sh#209]
While `ls | cat ` doesn't trigger any error, the command `ls | cat >a` does this only if the file doesn't exist:
![screen shot 2017-03-27 at 09 22 39](https://cloud.githubusercontent.com/assets/10199481/24345143/fbcbfd8e-12ce-11e7-9e88-41064aafe6d7.png)

**Comment by jzck** [comment]
@ariard yavais pas ca avant, t'as changé qque chose au parser ?

**Comment by ariard** [comment]
nan, je vois pas comment tu peux rentrer dans add_branch, il est appele que pour les if && case
