### ISSUE TITLE
bang with DQUOTE

### ISSUE THREAD

**Issue by wescande** [jzck/42sh#211]
on as pas la bonne sortie.
il faut penser a l'echappement simple et ou double qui n'est pas le meme

**Comment by ariard** [comment]
exemple plz

**Comment by wescande** [comment]
Echo "!"

**Comment by ariard** [comment]
nan mais meme la dessus bash fait pas des trucs posix, on ferme ?

**Comment by ariard** [comment]
normalement on a le meme comportement que bash
