### ISSUE TITLE
crash redir gauche

### ISSUE THREAD

**Issue by Gwojda** [jzck/42sh#25]
crash en cas de nombre impair > 2 de redir a gauche
==30637== Invalid write of size 8
==30637==    at 0x1000138C0: lexer_less (lexer_less.c:33)
==30637==    by 0x100013B81: lexer_lex (lexer_lex.c:54)
==30637==    by 0x100012DE8: lexer_default (lexer_default.c:24)
==30637==    by 0x100013B81: lexer_lex (lexer_lex.c:54)
==30637==    by 0x10001959D: interactive_shell (main.c:62)
==30637==    by 0x1000197D2: main (main.c:92)
==30637==  Address 0x100b4d340 is 0 bytes inside a block of size 41 free'd
==30637==    at 0x10003FAB5: free (in /Users/gwojda/.brew/Cellar/valgrind/3.12.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==30637==    by 0x100014823: token_free (token_free.c:24)
==30637==    by 0x1000138A5: lexer_less (lexer_less.c:31)
==30637==    by 0x100013B81: lexer_lex (lexer_lex.c:54)
==30637==    by 0x100012DE8: lexer_default (lexer_default.c:24)
==30637==    by 0x100013B81: lexer_lex (lexer_lex.c:54)
==30637==    by 0x10001959D: interactive_shell (main.c:62)
==30637==    by 0x1000197D2: main (main.c:92)
==30637==  Block was alloc'd at
==30637==    at 0x10003F671: malloc (in /Users/gwojda/.brew/Cellar/valgrind/3.12.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==30637==    by 0x100003F84: ft_memalloc (ft_memalloc.c:20)
==30637==    by 0x100003661: ft_lstnew (ft_lstnew.c:23)
==30637==    by 0x100013B5C: lexer_lex (lexer_lex.c:52)
==30637==    by 0x10001959D: interactive_shell (main.c:62)
==30637==    by 0x1000197D2: main (main.c:92)
==30637==

**Comment by jzck** [comment]
@ariard on va décaler la lecture de HEREDOC dans le parser je pense pour fixer ca
