### ISSUE TITLE
completion

### ISSUE THREAD

**Issue by wescande** [jzck/42sh#42]
problème quand trop de fichier a compléter.
ex "/dev/" puis tab

pas de completion sur un chemin avec path complexe
ex "/dev/u" puis tab qui doit renvoyer "/dev/urandom"

**Comment by m600x** [comment]
Il manque également la completion des buildin, je rajoute et fix.

**Comment by Gwojda** [comment]
Normalement c'est good sur mon dernier commit
(ref du commit : 11bc224 - nom : fixe #49)
