### ISSUE TITLE
retour d'erreur

### ISSUE THREAD

**Issue by wescande** [jzck/42sh#43]
taper un nom de path valide ne renvoi pas d'erreur dans le terminal (on a bien l'erreur dans le prompt)

**Comment by jzck** [comment]
par exemple? juste un path?

**Comment by wescande** [comment]
on n'a pas le même comportement que bash...
```
bash-4.4$ /dev
bash: /dev : Is a directory
```

```
➜  42sh git:(pda) ✓ /dev
minishell: internal execve error on /dev
➜  42sh git:(pda) ✓
```
