### ISSUE TITLE
lexing des brackets : erreur quand sur plusieurs lignes

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#45]
(ls | cat 
pwd ; ls )
token de sortie : tk_paren_open [ ( ] ; tk_word [ls] ; tk_pipe [ | ] ; tk_word [catpwd] ; tk_semi [ ; ] ; tk_paren_close [ ) ]
voila voila

**Comment by jzck** [comment]
Pour le coup c'est une liste de token avec plusieurs "instructions" comme on l'a defini par ailleurs. Je sais pas trop comment gérer ca! Je rajoute un token \n quand il faut et apres tu gere le subshell avec plusieurs instructions?

**Comment by ariard** [comment]
Yes, j insert des newline automatiquement a chaque ligne que tu m envoies, en avoir un en plus ca me derange pas, ou au pire j en ajouterai pas un en plus

**Comment by jzck** [comment]
sinon on peut faire:
- le lexer ignore les problemes de parentheses non fermées
- le parser rapelle l'input parceque la commande n'est pas complète
