### ISSUE TITLE
Pb lorsque binaire pas executable

### ISSUE THREAD

**Issue by wescande** [jzck/42sh#48]
En lancant la commande `/dev`, j'ai une erreur d'execution, mais le fork a eu lieu et le shell se trouve dédoublé.
Ex ci dessous, je suis obligé de faire 2 exit pour quitter

```

>  e3r8p16  ~/Documents/PersonalFile/42sh   pda  ./42sh 3>/dev/null


➜  42sh git:(pda) ✓ /dev
minishell: internal execve error on /dev
➜  42sh git:(pda) ✓ exit
➜  42sh git:(pda) ✓ exit
```

**Comment by jzck** [comment]
j'ai fix, par contre j'ai relevé une chose: quand je tape `objs/` il ne me reste que `objs` dans le argv au final, la faute au glob ?
