### ISSUE TITLE
completion

### ISSUE THREAD

**Issue by jzck** [jzck/42sh#49]
Il y a des choses qui ne marchent pas exactement comme zsh, ici je vais citer seulement ce qui n'est pas acceptable:

 - `/ho[tab]` me propose tous les fichiers dans / alors qu'il n'y a que `/home` qui correspond (ici zsh complete affiche `/home/` : à noter qu'il ajoute le / final pour pouvoir continuer de tabber directement) (le probleme à l'air d'etre lié a la complémetion "document" lorsque c'est en début de commande: `./src/[tab]` sort la liste des `./` ) !

- `ls < [tab]` ne me propose pas de completion (a noter que j'ai bien mis un espace apres le <, j'imagine que le [tab] collé au < doit poser un probleme de reconaissance de symboles du shell donc si tu ne veux pas l'implementer je comprends...)

J'ai trouvé d'autres erreurs mais je les soupçonne d'être des dérivées de celle deja citées.

Bon courage!

**Comment by Gwojda** [comment]
Normalement c'est résolu

Les problemes du genre "ls | [tab]" qui n'affiche rien sont voulu -> si on a pas assez de places pour tout afficher, on affiche rien pour ne pas s'y perdre
J'ai rajouté aussi la gestion des chemins commencant par un ~

**Comment by jzck** [comment]
je re-ouvre tant que c'est pas mergé, de plus `ls | ./src/[tab]` ne devrait pas etre trop grand ya pas grand chose dedans
