### ISSUE TITLE
reset des termcap

### ISSUE THREAD

**Issue by wescande** [jzck/42sh#50]
le shell ne restitue pas les termcap (ex ctrl + c apres avoir quitter le shell)

**Comment by Gwojda** [comment]
de ce que je vois, ca ne vient pas de l'edition de ligne, ni de la completion
Le job control utilise aussi les termcaps, ainsi que le builtin read mais en les utilisant je n'ai pas de soucis non plus et ca m'etonnerait que tu ai utilisé read

(tu as pas fait segv notre 42sh ? Si il segv avant qu'on remette les termcaps en place, c'est "normal")
