### ISSUE TITLE
grammaire

### ISSUE THREAD

**Issue by jzck** [jzck/42sh#53]
~~`ls | (cat)`~~
~~`(pwd) && pwd`~~
~~`pwd | (cat | cat)`~~
~~`ls ; ; ls`~~
~~`ls |`~~

**Comment by ariard** [comment]
(ls)) error de lexing ?

**Comment by jzck** [comment]
bump @ariard

**Comment by ariard** [comment]
if ls ; then ((VAR+=10)) ; fi

**Comment by ariard** [comment]
func() + newline
=> permettre l edition sur plusieurs lignes

**Comment by ariard** [comment]
antoine() while [ 1 ] ; do ls ; done
=> permettre commande compose en body func

**Comment by wescande** [comment]
@ariard 
c'est normal : ?

```
➜  42sh git:(master [ahead 1]) ✗ while [ $a ]
> do
> a=0
syntax error near unexpected token « a=0 »
```

**Comment by ariard** [comment]
jacques () { ( { ( pwd | cat -e ) | cat -e } ) | cat -e }
