### ISSUE TITLE
segv subshell

### ISSUE THREAD

**Issue by Gwojda** [jzck/42sh#55]
➜  42sh git:(master) ✗ (l(s))
syntax error near unexpected token `('
➜  42sh git:(master) ✗ (ls)
[1]    50656 segmentation fault  ./42sh 3> test

rapport valgrind :
==50727== Use of uninitialised value of size 8
==50727==    at 0x100005F82: exec_case_branch (exec_case_branch.c:30)
==50727==    by 0x100006A11: ft_exec (ft_exec.c:50)
==50727==    by 0x1000179FF: handle_instruction (main.c:75)
==50727==    by 0x100017C82: main (main.c:125)
==50727==
==50727== Invalid read of size 8
==50727==    at 0x100005F82: exec_case_branch (exec_case_branch.c:30)
==50727==    by 0x100006A11: ft_exec (ft_exec.c:50)
==50727==    by 0x1000179FF: handle_instruction (main.c:75)
==50727==    by 0x100017C82: main (main.c:125)
==50727==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==50727==
==50727==
==50727== Process terminating with default action of signal 11 (SIGSEGV)
==50727==  Access not within mapped region at address 0x0
==50727==    at 0x100005F82: exec_case_branch (exec_case_branch.c:30)
==50727==    by 0x100006A11: ft_exec (ft_exec.c:50)
==50727==    by 0x1000179FF: handle_instruction (main.c:75)
==50727==    by 0x100017C82: main (main.c:125)
==50727==  If you believe this happened as a result of a stack
==50727==  overflow in your program's main thread (unlikely but
==50727==  possible), you can try to increase the size of the
==50727==  main thread stack using the --main-stacksize= flag.
==50727==  The main thread stack size used in this run was 8388608.

**Comment by ariard** [comment]
premier cas, sur erreur de syntaxe ok

**Comment by Gwojda** [comment]
C'etait le cumul qui entrainait un segv
C'est réglé du coup ?

**Comment by Gwojda** [comment]
Ca a l'air réglé
