### ISSUE TITLE
Double redir a droite erreur

### ISSUE THREAD

**Issue by Gwojda** [jzck/42sh#57]
➜  42sh git:(master) ✗ ls>ret
➜  42sh git:(master) ✗ cat ret
42sh
42sh.dSYM
Makefile
TESTSHELL
donovan_segaults_06-02
includes
libft
objs
pdf
ret
sample
src
test
test_framework.sh
testmake
update_makefile.sh
➜  42sh git:(master) ✗ ls>>ret
➜  42sh git:(master) ✗ cat ret
42sh
42sh.dSYM
Makefile
TESTSHELL
donovan_segaults_06-02
includes
libft
objs
pdf
ret
sample
src
test
test_framework.sh
testmake
update_makefile.sh

retour attendu : 
42sh
42sh.dSYM
Makefile
TESTSHELL
donovan_segaults_06-02
includes
libft
objs
pdf
ret
sample
src
test
test_framework.sh
testmake
update_makefile.sh
42sh
42sh.dSYM
Makefile
TESTSHELL
donovan_segaults_06-02
includes
libft
objs
pdf
ret
sample
src
test
test_framework.sh
testmake
update_makefile.sh

**Comment by jzck** [comment]
c'est bon c'est résolu. pro tip: pour un test plus simple a relire il existe `pwd` x)
