### ISSUE TITLE
Tri glob

### ISSUE THREAD

**Issue by Gwojda** [jzck/42sh#63]
➜  42sh git:(master) ✗ echo */*
42sh.dSYM/Contents includes/builtin.h includes/builtin_read.h includes/completion.h includes/exec.h includes/ft_curs.h includes/ft_input.h includes/ft_readline.h includes/glob.h includes/hash.h includes/job_control.h includes/lexer.h includes/minishell.h includes/parser.h includes/types.h includes libft/includes libft/libft.a libft/Makefile libft/objs libft/pdf libft/README.md libft/src libft/update_makefile.sh objs/builtin objs/completion objs/exec objs/glob objs/hash_table objs/history objs/job-control objs/lexer objs/line-editing objs/main objs/parser objs pdf/21sh.fr.pdf pdf/42sh.pdf pdf/fdf.fr.pdf pdf/minishell.fr.pdf sample/assignement sample/brace sample/case sample/comment.sh sample/dir.sh sample/error.sh sample/file1 sample/for sample/func sample/if sample/if.sh sample/infinite.sh sample/laurier.sh sample/ls sample/mix sample/multiredir sample/redir sample/stack.sh sample/subshell sample/until sample/until.sh sample/until2.sh sample/while sample/while.sh sample/while2.sh sample/while_error.sh sample/yale sample/yale1.sh src/builtin src/completion src/exec src/glob src/hash_table src/history src/job-control src/lexer src/line-editing src/main src/parser TESTSHELL/simple_cmd TESTSHELL/stderr_ref TESTSHELL/stderr_test TESTSHELL/stdin_ref TESTSHELL/stdin_test

Les sorties doivent etre triées

Exemple sous zsh :
➜  42sh git:(master) ✗ echo */*
42sh.dSYM/Contents TESTSHELL/simple_cmd TESTSHELL/stderr_ref TESTSHELL/stderr_test TESTSHELL/stdin_ref TESTSHELL/stdin_test includes/builtin.h includes/builtin_read.h includes/completion.h includes/exec.h includes/ft_curs.h includes/ft_input.h includes/ft_readline.h includes/glob.h includes/hash.h includes/job_control.h includes/lexer.h includes/minishell.h includes/parser.h includes/types.h libft/Makefile libft/README.md libft/includes libft/libft.a libft/objs libft/pdf libft/src libft/update_makefile.sh objs/builtin objs/completion objs/exec objs/glob objs/hash_table objs/history objs/job-control objs/lexer objs/line-editing objs/main objs/parser pdf/21sh.fr.pdf pdf/42sh.pdf pdf/fdf.fr.pdf pdf/minishell.fr.pdf sample/assignement sample/brace sample/case sample/comment.sh sample/dir.sh sample/error.sh sample/file1 sample/for sample/func sample/if sample/if.sh sample/infinite.sh sample/laurier.sh sample/ls sample/mix sample/multiredir sample/redir sample/stack.sh sample/subshell sample/until sample/until.sh sample/until2.sh sample/while sample/while.sh sample/while2.sh sample/while_error.sh sample/yale sample/yale1.sh src/builtin src/completion src/exec src/glob src/hash_table src/history src/job-control src/lexer src/line-editing src/main src/parser

**Comment by wescande** [comment]
quand je fais `echo /`, ma sortie c'est `/`

Mais effectivement je n'ai pas de tri sur un `echo *`. je rectifie ça. si je passe a cote de quelquechose, dis le moi

**Comment by Gwojda** [comment]
C'est parce que les [etoiles] ne passent pas sur github x)
La commande c'etait echo [etoile]/[etoile]
