### ISSUE TITLE
subshell error

### ISSUE THREAD

**Issue by Gwojda** [jzck/42sh#64]
➜  42sh git:(master) ✗ (ls)
➜  42sh 42sh			TESTSHELL		libft			sample			test_framework.sh
42sh.dSYM		donovan_segaults_06-02	objs			src			testmake
Makefile		includes		pdf			test			update_makefile.sh
git:(master) ✗

il execute le ls au moment ou on remet le prompt
-> processus zombie qui se termine au meme moment qu'on affiche le prompt ?

**Comment by Gwojda** [comment]
➜  42sh git:(master) ✗ (ls)l
➜  42sh ls: l: No such file or directory
git:(master) ✗


Dans le meme genre

**Comment by jzck** [comment]
pour résumer la situation: `(ls)` dans bash affiche la sortie apres avoir affiché le prompt, et laisse l'utilisateur sans prompt.
Le notre affiche ca au milieu du prompt, pour moi le comportement est cohérent par rapport à bash.

ps: une fois qu'on aura passé l'appel de git pour le status dans le prompt en mode `command_getoutput` je suspecte la sortie du ls de se faire apres la fin du prompt (@wescande si tu peut te charger de faire ca c'est cool)

**Comment by Gwojda** [comment]
C'est résolu de toute manière, maintenant (ls) a bien le meme comportement visuel quel ls
je close
