### ISSUE TITLE
segv redirection droite  "ls -- 9>file3 [1]"

### ISSUE THREAD

**Issue by Gwojda** [jzck/42sh#74]
➜  42sh git:(master) ✗ ls -- 9>file3
[1]    84225 segmentation fault  ./42sh 3> test

**Comment by jzck** [comment]
ca a l'air de venir du parser @ariard

**Comment by ariard** [comment]
normalement c est bon sur le commit que je viens de push

**Comment by Gwojda** [comment]
Réglé
