### ISSUE TITLE
prompt coller avec heredoc

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#78]
cat << a ; cat << b
> a
> b

sortie
ab->42sh git:(master) x

**Comment by Gwojda** [comment]
C'est a l'execution, l'heredoc de maniere general marche mal
Si je fais cat << a
bbbb
aaaa
a
il doit me sortir 
bbbb
aaaa

Et il affiche juste un a sans retour a la ligne

**Comment by jzck** [comment]
@ariard: il faut que le heredoc_queue->content soit un `char **` pour que quand on `strjoin` le changement se repercute bien dans le `t_redir`, je vais voir si je peux le modifier

**Comment by jzck** [comment]
@ariard j'ai l'impression que le parser qui n'arrive pas a `strjoin` dans la `t_redir`, p-e que c'est le merge qui a enlevé des choses ?

**Comment by ariard** [comment]
@jzck j ai une fonction show_heredoc qui m affiche bien la data de heredoc juste avt ft_exec a partir de node->data.cmd.redir, normalement j ai commit & push la function de show samedi
