### ISSUE TITLE
historique avec while passe en fichier

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#83]
le prompt m affiche
wwhile [ 1 ] ;do ls | catdone

pour en fichier passe 
ls
while [ 1 ] ;
do
 ls | cat
done

**Comment by jzck** [comment]
faudrait désactiver l'historique pour les fichiers en mettant un `if (fd == STDIN && SH_IS_INTERACTIVE(data_singleton()->opts)` je pense

**Comment by Gwojda** [comment]
ec4845da18c4d1a0274258bcb00b5fdf41dae8c7
Resolu sur ce commit par jack
