### ISSUE TITLE
completion rewrite the buffer when we try to complete on multilines

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#88]
"./write_on_stdout_and_stderr TOKEN_out TOKEN_stderr | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin"

then try to complete again and buffer is written again like : 
"./write_on_stdout_and_stderr TOKEN_out TOKEN_stderr | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin ./write_on_stdout_and_stderr TOKEN_out TOKEN_stderr | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin"

**Comment by Gwojda** [comment]
Normalement c'est resolu, ou alors c'etait pas le meme probleme que l'issue #85

**Comment by Gwojda** [comment]
Je close, normalement c'est resolu
