### ISSUE TITLE
from Shelltester : a lot of pipe provoke abortion 

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#89]
"/write_on_stdout_and_stderr TOKEN201703111730_stdout TOKEN201703111730_stderr | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin | ./read_on_stdin"

then "abort"

Make a git clone of Shelltester and take the binaries "write on_stdout_and_stderr" and others to manually test

**Comment by wescande** [comment]
Jack, est-ce que cela peut etre du au fait qu'on ait limité le nombre de fd a 9 ?

**Comment by jzck** [comment]
on a trouvé que la fonction d'affichage `btree_print` ABORT si l'arbre est trop grand. en commentant on n'arrive pas a reproduire.

en ce qui concerne les fds, les fds produits par `pipe()` sont dup2 sur STDIN/STDOUT et close ensuite donc ils n'existent pas par la suite
