### ISSUE TITLE
assignment word en 2eme position, with export

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#93]

**Comment by jzck** [comment]
c'est quoi le problème? s'il y a des assignment_word en mauvaise position je pense que c'est au parser de les traiter comme des word

**Comment by ariard** [comment]
Le conflit, au niveau du lexing il respecte les regles pour etre consideres comme des tk_assignments_word mais la grammar ne prevoit pas une cmd_name suivi d un assignment donc je sors une faute au parsing

**Comment by jzck** [comment]
bah je pense que dans ce cas la du doit convertir le assignment word comme un word
