### ISSUE TITLE
Shelltester : ./write_all_arguments_on_stdout \{1..2} {1\..2} {1.\.2} {1..2\} se mettre d accord sur lexing

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#94]
TOKEN de sortie : 
        token_print.c 24 token : TK_WORD data [./write_all_arguments_on_stdout]
        token_print.c 24 token : TK_WORD data [{1..2]
        token_print.c 24 token : TK_LBRACE data []
        token_print.c 24 token : TK_WORD data [1..2]
        token_print.c 24 token : TK_RBRACE data []
        token_print.c 24 token : TK_LBRACE data []
        token_print.c 24 token : TK_RBRACE data [1..2]
        token_print.c 24 token : TK_RBRACE data []
        token_print.c 24 token : TK_LBRACE data []
        token_print.c 24 token : TK_WORD data [1..2}]

**Comment by jzck** [comment]
je close #51 et j'amene la discussion ici.

le commit ci-dessus change un peu le lexing on va voir si ca suffit a mettre tout le monde d'accord

**Comment by jzck** [comment]
je pense qu'il me manque des éléments pour bien comprendre le lexing des '{' et '}' faudrait qu'on se mette d'accord, la doc posix en parle ?

**Comment by ariard** [comment]
Exact, la doc posix sur la partie grammar, non je lis la partie expansion

**Comment by jzck** [comment]
On a choisis la convention suivante, pour avoir des `{` et `}` qui servent a grouper des commander il faut un espace apres (respectivement avant) qui donne des choses comme `{ ls ; pwd } | cat`.
S'il n'y a pas d'espace le `{` ou `}` servira dans le globbing!
