### ISSUE TITLE
modification maligne de l'historique :  (cd ~ ; dd if=/dev/urandom of=.42sh_history  bs=2048 count=10)

### ISSUE THREAD

**Issue by ariard** [jzck/42sh#98]
Puis apres les caracteres ne sont pas effaces quand on joue avec l'historique

**Comment by jzck** [comment]
c'est quoi le principe en fait ?

**Comment by Gwojda** [comment]
Le comportement que j'ai fait : 
Je parcours ma ligne lue, si jamais je trouve un caractère non ecrivable c'est qu'il y a une erreur dans la ligne c'est que la ligne va entrainer des décalages et donc que le fichier est corrompu

-> Je vois pas comment protéger de l'edition du fichier par contre, meme zsh ne le fait pas..
