### ISSUE TITLE
globbing * dans for

### ISSUE THREAD

**Issue by jzck** [jzck/42sh#99]
`for file in *; do echo $file; done` ne fait pas la sortie attendue

(il fait la sortie identique a la premiere colone d'un `ls`)

**Comment by wescande** [comment]
bizarre.
j'ai fait des tests de debug dans le glob et je ne vois rien d'anormal : 
voici ce que j'ai en sortie de glob sur l'étoile dans le cas du for :
```
 2554               glob.c 92 input : *
0 - 42sh
1 - donovan_segaults_06-02
2 - includes
3 - libft
4 - Makefile
5 - objs
6 - pdf
7 - sample
8 - src
9 - STDBUG
10 - test_framework.sh
11 - TESTSHELL
12 - update_makefile.sh
```
et voici ce que m'affiche le for : 
```
➜  42sh git:(master) ✗ for file in *; do echo $file; done
42sh
includes
Makefile
pdf
src
test_framework.sh
update_makefile.sh
```
Il en manque exactement 1 sur deux...

**Comment by ariard** [comment]
c est le for qui deconne, je viens de tester avec un echo * a l interieur d un while je les ai tous. C est normal je suis en train de revoir des trucs sur setenv, local_var, assignement_word

**Comment by ariard** [comment]
merci wescande
